apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lucle
spec:
  encryptedData:
    jwt_pkey: AgAcNWUDjHX8jwgmTsZWVVKmkpisJ+rfjY243APoOYMmfmkfzWcAKgIV6dIlbSLb33GcKbGj+2aWR65uSoGOY+1NOsVvUMgHF33YrY8lGwTkgqUEPlTQd+bjGFhAsAqeC/caKNOCYzcC3qmoZ/DWKCAh08SpUr3hJ/4ugy+bEOip1owsx7InK5+UmskKgCeBMRH7oETS0aUTS5wL3F8z7vU9M0N/arC5K1t1mwlQfPGx+4V/QgpXUmZqsNPrmKBdKqv9iUzgZm2pcQ9w4U/K4oocad0YPKRVWVhS3JvaT8RqUQFuEs7PTQ8LmE8fbI0yhoCtu2E1eOucSB513jmaQokgOIfRjf0phFhZL0SMZ37nAJ2UtkBuch+T9lifEHXlUW0Ary7HzAmriHWf3K1iFEtmbzxDuSK6lI3nxLLhUM8epC0s1+uxTakvoaqpnwUgtScxC333R5I1ES0HyGTgd9bdBS6phJ/3Ye2tHsf2bb27DiQp6lRsuUGidfFI2e/UvNCsFANRLYCGwLSlav282ThchgXhPFfDM9EP7dTlJVqfv5C2i4bfMB6USlEM+QHInBhonGPcijn7qn5Z0Xapv5epKD3jy+ZOkdzKXh7tEoQdUUS1SyGlh2arX+sZW5p5T2A4grUX3Z88ZaP2mJvGkp/BGPh6J371B3cTkgUAmPE75dm8+bIryxGljeGLZNgSHTxdA6+gCCTDLeCIM4KAMnGpV7HSnLBjldeWCq/UIbwCt0afgTiIgQ6TLaZMWZ2/X2kpSdKxP/CHY6LFD9MyMr7eQpN+ktaGWsch0F2ygG4Lu/Ws/62CamOl3Jff9CAD7xPLKFTZi7j/f2Y0qRxMUx7eVhNRM7TlGt8OdG0yqVcLiZtIp/4jQZq9dAbRn2NXQ59LAVR5YvL+f2uZbR2zHW7rcMZpv6OgpJXQg8LojSbjQmLzn9QI+ddU3LKszUW2fqCSKkMvqE8/N/gb5pYxVGU/fEGx2X4szYbH+3NjLhyC
  template:
    metadata:
      name: lucle
      namespace: lucle
