apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lucle
spec:
  encryptedData:
    jwt_pkey: AgBSdESb/uZofIO5KOydaq27RoL6mGpbUTzM9g0T6QbJiqYPnvvfRDh/dB2lyOAyteV3ZLi4Jnv5ZfSFtvvjyjNs44mLnrkzCPUGd5ooXR/LeAXWq0j1Ncn76/WLdIXtiSoYq7z5bo1qVNVCu8mNYY9LMYcjLuvlER+MhRYH9h3gKyKhB8g6D9y8sSagqtFnMMiLhiVLWZhMjhd0a6iMY+PsGbemCZjtwcM6rVnmyuQBR2/GUPe+SrlRHXkq7UTwqsLtRbg9LGsFGESeY45yEf+0x9qDzIQz6b5DfXVOxXNFycxOdZdohbeuUGpYlmfCsAaORU6Rxq06tGrYwLJltE8lNnj7rgmruvS1H2/edj2HsZ9msNl5de5nH9idw9nUem2cqQWLgZpbu1WEm+4hiYDAne+iXBxI1llQ479i9mv5pw+doqWvoQZzSx6VnSXprB+zPzK5n90O93FlrbdKVlhgmBvwOixBql4s91aKveJIzhZnEKllDuzwJYsmlpkrzAjYnnFxNVoAXGuICss4t05K4HgN1XDOTG9CsarZwwZY/leoqWNwFd0bDyjByLkAwTyIP6l9ao6W4cvT5ZEW9xEONcu5UphglnpedITvR57pOcIGk85HBs6o++9lOKKob+88LwyUH73lvTsccANvTZA6pjDsKpWitq3ucugxjmoPIU3WCGmFYVLbIcZMuM+bAfnR1xzn5d6MWZNNz0BeH4W0tkrWDbzyYSF4/xkQGtjtA9WdgBXDCQB7xJznE0C8fcMlwmTfis5pz56cunaFuXXOuPuqy9Pv+sqUBPkETYbaYpDqjr2ET1CK36+A8OoUWBVlnnitfiuIWDh4J1WNWrYTGDQ0Q9Rvgg==
  template:
    metadata:
      name: lucle
      namespace: lucle
