apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: lucle
spec:
  encryptedData:
    jwt_pkey: AgBb+yPLiIUenUZXhkd3LtSoChyDcwgjBm+1iplCPrg/A+OJ/8MfQot94X9lgfNsrcbW1hrx12nBPUzqt0nalOKu3bM0m/gvgdUj4X9cla1sgiSTWU+C1usQf3iKL9/c4wfmQQGyEPEtgJ1taQ1uAKizxNtyJGCirlAnSMUI0KR9/qdlDJz/r+yWiGU9xNsH0Z7yPX4DWAZAnv1xObAy7PCESsNv4qDyAuFQrZA6hofNKbc9PNsYgwiw/23pwpS0Wi4XWMybNfxfHmbz3llYpgAL0ORPlZrHVsDs8mXAPzvZVvTorRFnxpHqqLKX6shjAIZ0PUwgxtTkJVsGWWrcxyE/2d/TE4cp4JY67FIRIg+/igRxHEZ/fNMkSjEQG7upvjkAcQfiyqxHsyx/b1Y5zGHB380iPJIiqAgAROoqifcARFECYtWz7ZqCzE0fI7WYC3eGxxceReLBNIdvY3iuHTDq8TUuXQ16zkG3XcYnWNhduj/K1lSO5kMM8X667H2kE0dZ/9idaMwzAVwvkKBwN2F5Hih7TK2uQ5kplYA6fL+PWJgCX2NqzlkVi9Sf+1S7QfaZhaShmhvEIgp9GCXiZg7kMWnw5gJMRFs0OxaG846kVfNqsVCgOYtxdpJs7rQpU0W3g1GR5DqJmt+i/bf0gwU6n8hMxnI8ktxeQV4LWpNSKznah4H/UVj6R4rVWITEFvpmwYzLI1CHPe/AvXu9U19YDoWZtqK9QBei015wlvw66QVI0CsNVWvtVPIvQ4w0vAxnVNQgIb3D83gUUTEN76bW0uHOFOXCSpioReabau5i6Tukl4ICpuBhvVw0utZnkd2qhzCZheImb5iFSQx7A2BokjWqF2T5Fag1exa0qEKtco7pu1SZIRCDs4JPv4RCDaztyel+TRaYdlApE09yVUO7kiEpS0bfueD9EMvwJCJEt0GGtytdPDk0nqfirxvQ+SDqSoFI1AWMyPQn75exRe7kopGUmcFLUR2DsN6vTTNd
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: lucle
