apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedupdate
spec:
  encryptedData:
    jwt_pubkey: AgBo4E6jIsNkYxlzYXUz5GJTY5d5Il2pKDWnnTm+kqnA9HbO1fTz/Kx2HUWCD4bTEETbgpHBfKSgDZKuiGxR6EbCMXnpZzAwIr50LVGc+l0hndtJ2QveB2zkvl4tK/kzVmDGI6t5Xdr+aqPMSZZb/f+f23h/FyLGo9FyhFbV9rx5cf+/1uIL4YlmhtlSMHyfh7N14HQtKPqJbhPt55pCSnKrlxW2wEVv3T4pLeYBJZ0/1qNVYuKXnRu76cW/K4ZDe1epO8EDojbwcUFxnkgwK3l03GkPiZchocztRq5DYCCAzr+miyydv8EbjVb3TgdsdAA85gINzUwLibZKjUcpuCBxMBfY16oN7f+NV9ae0kv5ZkMSRGOCBaWOACNrIBBu4G9DFPf9oLrSHPETv81Kjy4LHDKGOKIh2YBLlXGCSbZw8nndwvGmcVRqAt8Vk3JVG5/8mDDowO9g+RQvXfRH80ylCzcGlhYa4UiDQoFRsIxEfGXCHqW6vLL6N9MJdLVrAUUt/SjQKaQ4v6wkCOEHOdWgV9nHWnPa5VTciJqvpREZWJZY8h8aQJVhRc2wcsJKXMRKcqqVFHsszJWClwM31ZKA3A7bNMtwDN080DltsNXwGUrv9kyR75JKGfOTAuB9Lgw4uuRQi/pP3ELbvow680ciaF/Bl9JKZ9kqPxkwYCYJbwIqGt56agahjPsLSL5gXrJJa+4l6fsgTE+RmPPbuV2pXmArNis9+kFlehSCtDfvVih1z28CsSOx99ozvPPC8qVnwpZbDcrmIgztFtvDJtBkjxAsG3xB5SyLRcHZIFWkcCZa+XL87Jw/GdVsF90i0qstQ5Vi9SjCP3hEjOKov2NZrA==
  template:
    metadata:
      name: speedupdate
      namespace: speedupdate
