apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedupdate
spec:
  encryptedData:
    jwt_pkey: AgBdEBYYal8vuucNELF8YSl71XMWRXoL5NT5q6ZKVyU90G5kBRFaNTLjjwWGX37+Zcd/HKN6y3wVM/lITP49woLJx/3aq5gVDeLsTBbYCeOZSeFa9sDIxvEV6ky3zP1Nl5VltrXR4cWaTLulRtqEAygmknA0BaAl0wJ1ttrgmcscAUcUKeyIZ8WFFdqtgrJbDy4yi/fTk5TBL7YuFDkIo6HlOGaaK3VA8x1hl0kBFwDMtx3s/WAUivHDrlUhWM+To8Rdhk1tynqQHcthlIllybLBe0UScWZv3JzKaVShth4vlbQZfvGsz5e1SgwN2viyzM/BntA7hGbc5QGwrVmHxngMwElGb7hcz3zaHAKSn4XYnzzvtWJxc/RMWUE7TptbKNnOJWy2hVUUHf7Yk7tEHqUBR1Lh8aB/WprpzZK1wctfLaLcnHg/Ib6UIuuyzVEZU9M36Ym0G1i2pRRcokvnSDbxuywtRlODxpMY76Zyvc61nEDsxgZOEIdHNCYaaTraHM7eP4WOOW0HNnELah4NWfUrzzIGOmRjnskXcHfUPgCne9LSsuBZ0egGmZTQX6ZjGCzcFjjUJwsryQyskSBC3JAWdQmODZcrqQkrwnyhCl/ag6aP5I09zkcrSE8DuUQbXAUCEWuXYpQLGPuEgjxz6sX5jasi6ppETElgfkx5KQBtNeFPgQB35TesL7VN+ZHZhvCsE9EKVYeSCTZGcZhO6y+WwIZe2Xtp4aohZnBk33NItlNGM1rnbrUMn0z2sX6fM7oLLdLJuf5OBjIT6QVMOl/r9lB+fZOCkJAGuzmS8VRjwHTfqL+9EL7fsHinBDGns0NrUP9K8roasGZDlAgrQINQnsXUqCUivsF0J5Zkw+tYEMnplwCkH3TLcU5bDeoMPrTRVLAi+tN8aYR5dfCpdMBhCT57Jim15BIjtBrkM+GJZZlaiusez5OweBWUJAKGU1Jf8fGiBECozo5rqnK9SkuHh/JPceEZICI7t/GhsSG5
  template:
    metadata:
      name: speedupdate
      namespace: speedupdate
