apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedupdate
spec:
  encryptedData:
    jwt_pkey: AgB4GW48W7UGCLvqig5AY+r3VyQlQpc4eQVARMcU4u2rMID02hStwhiKZDAMfCwowwpchGGzbQDh8l8yoV3LXli0kG5aFLV0wB9xaOahHoFgIQ+IZVawQ59TIprP6T/q7TtKpzFrsJEZ7jCmI/WbBQxlcHZ54bF0b7Da9mxXuie2M9L+C3cOdMc79RYkJKCZEWtw3oOmUik5bWqA2zNZ02z9g3XumJK38SOYgIgb7zlmfXVq11JioqLmC4U2XpQDmdVch7E7OAOGCSDPo2zPgcfUbpJAw5PFSdJv+PrzoYT8Q3GrcYkbt5stGVwb8FVMiL1tLdQnjLXFol5NWx/prQIIjkftTKB0+yE+I9TGKgU1UH3Qw79YJExEUs73+IzKHjXeCnSGYjlcngPvc5wfH+7rcPseWrEPMPgwX9GOjutngmxZZVQl7h60cM4jXfjjSf53vsR/8nKKsv3W9BBJBqsCBDbIEdSOFqwKbyxgiOiYIO6cUx91XR/re35SzrfrukY/H6KzCdbV++umxb15b+PSjvsMqX7fLunUvjw+0+FWC9XkpJZ/jfZrHcoIRazU9b8c+uqa90gEqna0mWK3jNGWtP/9sCvCgBpDnYZkReUN5nu2+0mhLYyHKSv/ILuj9GRsHqmrPvm8PlAHzAGE+NrDpK3FupLUQmj7XKYQ6rJqI8YIDIVPWfxWbIu3i7pJcMgzIFkq3O8eP+pwwPKlCXPT0mhOEAjxnTu1kraYMVhnfsRNnVNurHotGgxAQmwpZdWZRHx0Xcppb27uxcx4LHJv04OhgOw/NhJf1spCz2vYRlH7Ifbm7Y6d7N+EAm1qPXDroCLVLZFm3/7KJ9htdNmmTaKFYA8cgTPahp77WRY6rSqsEYdWs98pxmbxsvvt0HOs2rGDrBMuX3zd4e4VMAQDZl7aBeDXeFn5oI/vZQdyS5d1ETUwgeVJXqoLhTzhBoxejtrKdsjKjIk1GOJ+jwNbaL4xFcjAdqieEyumXtoo
  template:
    metadata:
      name: speedupdate
      namespace: speedupdate
